### PR TITLE
re-add networkinstall

### PR DESCRIPTION
**Pull request by Plailect**
The introduction of `servefiles` is a neat concept and a pretty useful idea in some circumstances, but it does not fully replace the workflow that was provided by `networkinstall`. 

Unlike `networkinstall`, `servefiles` requires files to be written to the disk, manually opened, and manually scanned by the target device *(the system I am using, WSL, is CLI only and cannot have the QR codes open automatically)*.

I'm not claiming that `servefiles` does not have any uses, but I do feel that its introduction does not warrant the complete removal of `networkinstall`.

### CODE REVIEW

**Comment by Steveice10** [comment]
Network installation with the provided tool, sockfile, also required files to be written to the disk. Just as an alternative could have been written to provide files not on-disk, an alternative for servefiles could also be made that serves a file over HTTP from memory instead of a file.

**Comment by Plailect** [comment]
I mean that with `servefiles` a png must be written to disk that I'd then have to manually open. This is a lot of extra steps for seemingly no benefit. 

Entering the URL manually on the 3DS is a pita compared to just entering the IP for the CLI.

Why was `networkinstall` removed, and why can both not exist side by side?

**Comment by Steveice10** [comment]
As of the latest FBI release, servefiles does not write a PNG to the disk, it displays it from memory. And once again, once you enter it once, you can simply press X to repeat the request later.

It was removed because it's more code to maintain versus one means of installation over a network, it was reportedly much slower, and it did not use a standard protocol, where as this uses simple HTTP.

Given the response to its removal, I will have to take some time to rethink how remote installation in general should work. I'd like there to be a single unified method that satisfies the use cases of both, which is why I added convenience features like remembering the last URL.

**Comment by ihaveamac** [comment]
just throwing this idea out there, you could have servefiles send a list of urls to cias to FBI rather than generate a scannable QR, and have it use them to download and install the contents.

**Comment by Steveice10** [comment]
That... sounds interesting. Will consider it.

**Comment by Steveice10** [comment]
Based on that idea, how does this sound:
* An entry on the main menu called "URL Install" that opens a menu containing:
    * Scan a QR Code
        * Turns on the camera and looks for a QR code
    * Receive URLs over the network
        * Opens a socket server and waits for a remote connection to provide URLs
    * Manually enter URLs
        * Opens the software keyboard to type a list of URLs manually
    * Repeat previous request
        * Uses the URLs from the last URL installation operation

**Comment by ihaveamac** [comment]
looks good to me. it could probably be improved to like "URL/Network Install" and "Receive URLs/Files over the network", since the way it sounds seems like the user can only send actual urls instead of local CIAs/tickets. but that could just be me

**Comment by Steveice10** [comment]
Changes have been implemented.

**Pull request closed without merging**
